### ISSUE TITLE
在windows 10上设置书签路径，总是提示 "保存失败。。。“

### ISSUE THREAD

**Issue by simonSaysGit** [vst93/bookmarkSearch-uToolsPlugin#1]
我设置的路径为 C:\Users\bo.sun\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default

尝试：
1. 使用管理员权限启动uTools  无效
2. 怀疑上路径中含有空格的问题，改成：C:\Users\bo.sun\AppData\Local\BraveSoftware\Brave-Browser\"User Data"\Default
在User Data前后加了双引号。无效
3. 怀疑上斜杠的问题，换成了 / 无效

![image](https://user-images.githubusercontent.com/58597749/70368088-b31dbc00-18e1-11ea-9760-9b50edd82bb0.png)

**Comment by simonSaysGit** [comment]
已经解决了。
路径不能设置到文件夹上，要直接指定到书签文件上。
如下：
c:\Users\bo.sun\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default\Bookmarks

点保存时，先会出现一个“保存失败。。。”的提示框。不要急，大声念yamede三次，就会出现保存成功的提示。

这个操作中最重要的是，念的时候一定要虔诚，声音洪亮。

**Comment by vst93** [comment]
![image](https://user-images.githubusercontent.com/9971164/70379259-8ad7a100-1965-11ea-91b2-97fb7d2f9ee9.png)
下次更新（有的话。。。）我加下提醒
